## Overview of the mapclassify API

There are a number of ways to access the functionality in `mapclassify`

We first load the example dataset that we have seen earlier.

In [1]:
import geopandas
import libpysal
import mapclassify

Current `mapclassify` version.

In [2]:
mapclassify.__version__

'2.5.0+8.g34341a22.dirty'

In [3]:
pth = libpysal.examples.get_path("columbus.shp")
gdf = geopandas.read_file(pth)
y = gdf.HOVAL
gdf.head()

AREA  PERIMETER  COLUMBUS_  COLUMBUS_I  POLYID  NEIG      HOVAL  \
0  0.309441   2.440629          2           5       1     5  80.467003   
1  0.259329   2.236939          3           1       2     1  44.567001   
2  0.192468   2.187547          4           6       3     6  26.350000   
3  0.083841   1.427635          5           2       4     2  33.200001   
4  0.488888   2.997133          6           7       5     7  23.225000   

      INC      CRIME      OPEN  ...  DISCBD          X          Y  NSA  NSB  \
0  19.531  15.725980  2.850747  ...    5.03  38.799999  44.070000  1.0  1.0   
1  21.232  18.801754  5.296720  ...    4.27  35.619999  42.380001  1.0  1.0   
2  15.956  30.626781  4.534649  ...    3.89  39.820000  41.180000  1.0  1.0   
3   4.477  32.387760  0.394427  ...    3.70  36.500000  40.520000  1.0  1.0   
4  11.252  50.731510  0.405664  ...    2.83  40.009998  38.000000  1.0  1.0   

    EW   CP   THOUS  NEIGNO                                           geometry  
0  1.0  0.0  1000.0  1005.0  POLYGON ((8.62413 14.23698, 8.55970 14.74245, ...  
1  0.0  0.0  1000.0  1001.0  POLYGON ((8.25279 14.23694, 8.28276 14.22994, ...  
2  1.0  0.0  1000.0  1006.0  POLYGON ((8.65331 14.00809, 8.81814 14.00205, ...  
3  0.0  0.0  1000.0  1002.0  POLYGON ((8.45950 13.82035, 8.47341 13.83227, ...  
4  1.0  0.0  1000.0  1007.0  POLYGON ((8.68527 13.63952, 8.67758 13.72221, ...  

[5 rows x 21 columns]

## Original API (< 2.4.0)


In [4]:
bp = mapclassify.BoxPlot(y)
bp

BoxPlot

   Interval      Count
----------------------
( -inf, -0.70] |     0
(-0.70, 25.70] |    13
(25.70, 33.50] |    12
(33.50, 43.30] |    12
(43.30, 69.70] |     7
(69.70, 96.40] |     5

## Extended API (>= 2.40)

Note the original API is still available so this extension keeps backwards compatibility.

In [5]:
bp = mapclassify.classify(y, "box_plot")
bp

BoxPlot

   Interval      Count
----------------------
( -inf, -0.70] |     0
(-0.70, 25.70] |    13
(25.70, 33.50] |    12
(33.50, 43.30] |    12
(43.30, 69.70] |     7
(69.70, 96.40] |     5

In [6]:
type(bp)

mapclassify.classifiers.BoxPlot

In [7]:
q5 = mapclassify.classify(y, "quantiles", k=5)
q5

Quantiles

   Interval      Count
----------------------
[17.90, 23.08] |    10
(23.08, 30.48] |    10
(30.48, 39.10] |     9
(39.10, 45.83] |    10
(45.83, 96.40] |    10

### Robustness of the `scheme` argument

In [8]:
mapclassify.classify(y, "boxPlot")

BoxPlot

   Interval      Count
----------------------
( -inf, -0.70] |     0
(-0.70, 25.70] |    13
(25.70, 33.50] |    12
(33.50, 43.30] |    12
(43.30, 69.70] |     7
(69.70, 96.40] |     5

In [9]:
mapclassify.classify(y, "Boxplot")

BoxPlot

   Interval      Count
----------------------
( -inf, -0.70] |     0
(-0.70, 25.70] |    13
(25.70, 33.50] |    12
(33.50, 43.30] |    12
(43.30, 69.70] |     7
(69.70, 96.40] |     5

In [10]:
mapclassify.classify(y, "Box_plot")

BoxPlot

   Interval      Count
----------------------
( -inf, -0.70] |     0
(-0.70, 25.70] |    13
(25.70, 33.50] |    12
(33.50, 43.30] |    12
(43.30, 69.70] |     7
(69.70, 96.40] |     5

In [11]:
mapclassify.classify?

Signature:
mapclassify.classify(
    y,
    scheme,
    k=5,
    pct=[1, 10, 50, 90, 99, 100],
    pct_sampled=0.1,
    truncate=True,
    hinge=1.5,
    multiples=[-2, -1, 1, 2],
    mindiff=0,
    initial=100,
    bins=None,
)
Docstring:
Classify your data with ``mapclassify.classify``.
Input parameters are dependent on classifier used.

Parameters
----------

y : numpy.array
    :math:`(n,1)`, values to classify.
scheme : str
    ``pysal.mapclassify`` classification scheme.
k : int (default 5)
    The number of classes.
pct  : numpy.array (default [1, 10, 50, 90, 99, 100])
    Percentiles used for classification with ``percentiles``.
pct_sampled : float default (0.10)
    The percentage of n that should form the sample
    (``JenksCaspallSampled``, ``FisherJenksSampled``)
    If ``pct`` is specified such that ``n*pct > 1000``, then ``pct=1000``.
truncate : bool (default True)
    Truncate ``pct_sampled`` in cases where ``pct * n > 1000``.
hinge : float (default 1.5)
    Multiplier f

In [12]:
mapclassify.classify(y, "User_Defined", bins=[0,50, 100])

UserDefined

    Interval       Count
------------------------
(  -inf,   0.00] |     0
(  0.00,  50.00] |    40
( 50.00, 100.00] |     9

### Finding bins for new data

In [13]:
r = mapclassify.classify(y, "User_Defined", bins=[0,50, 100])

In [14]:
r.find_bin??

Signature: r.find_bin(x)
Source:   
    def find_bin(self, x):
        """
        Sort input or inputs according to the current bin estimate.

        Parameters
        ----------

        x : numpy.array, int, float
            A value or array of values to fit within the estimated bins.

        Returns
        -------

        right : numpy.array, int
            A bin index or array of bin indices that classify the
            input into one of the classifiers' bins.

        Notes
        -----

        This differs from similar functionality in
        ``numpy.digitize(x, classi.bins, right=True)``.

        This will always provide the closest bin, so data "outside" the classifier,
        above and below the max/min breaks, will be classified into the nearest bin.

        ``numpy.digitize`` returns :math:`k+1` for data greater than the greatest bin,
        but retains 0 for data below the lowest bin.

        """
        x = np.asarray(x).flatten()
        right = np.digiti

In [15]:
r.bins, r.counts

(array([  0,  50, 100]), array([ 0, 40,  9]))

In [16]:
r.find_bin([7,0, 51, 33])

array([1, 0, 2, 1])

Note that `find_bin` does not recalibrate the classifier:

In [17]:
r.bins, r.counts

(array([  0,  50, 100]), array([ 0, 40,  9]))